default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: Daycare_backend_development

test:
  <<: *default
  database: Daycare_backend_test
